services:
  webpage:
    build:
     context: .
     dockerfile: docker/Dockerfile

    ports:
      - 4000:4000

    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .github
        - action: rebuild
          path: Gemfile
        - action: rebuild
          path: Gemfile.lock