name: Jekyll site CI

on:
  pull_request:
    branches: [ gh-pages ]

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1
      
    - run: ls _site
    
    - run: sudo chown -R $USER:$USER /home/github/actions-runner/_work/Cevi-Tools-Webpage/

    - run: |
            echo "{}" > _site/firebase.json
            
    - run: ls _site

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.CEVI_TOOLS_FIREBASE_PREVIEW_TOKEN}}'
          channelId: preprod
          entryPoint: _site

